reference_card: data/RC_RGB_v1.2.4.jpg

input_images: data/input_images/v4
calibration_images: data/input_images/v4
camera_id: default
logs: data/log.txt
use_ui_for_calibration: False

use_sift: True
show_sift_plot: False
show_color_correction_plot: False
apply_color_correction: True
show_extracted_circles: False
