reference_card: data/RC_RGB_v1.2.4.jpg

input_images: data/input_images/
calibration_images: data/input_images
camera_id: iphone
logs: data/log.txt

use_ui_for_calibration: False
use_sift: True
show_sift_plot: False
